### PR TITLE
Pin zephyr to a particular commit in west.xml

### PR DESCRIPTION
**Pull request by anujdeshpande**
Hey @cfriedt - I had to make changes to the patch to be able to apply it. Does this look better? I checked if it applies correctly, but still figuring out the rest of the setup - so can't verify.

### CODE REVIEW

**Comment by anujdeshpande** [comment]
Before fixing the patch, I got the following error on my git apply

```
base) ➜ zephyr (7162786f83) ✗ git apply --verbose ../greybus/zephyr-dynamic-pthread-stacks.patch
Checking patch include/kernel.h...
error: while searching for:
 */
#define K_INHERIT_PERMS (BIT(3))

#ifdef CONFIG_X86
/* x86 Bitmask definitions for threads user options */


error: patch failed: include/kernel.h:488
error: include/kernel.h: patch does not apply
Checking patch include/posix/pthread.h...
Checking patch lib/posix/Kconfig...
Checking patch lib/posix/pthread.c...
Checking patch tests/posix/common/prj.conf...
Checking patch tests/posix/common/src/main.c...
Checking patch tests/posix/common/src/pthread.c...
Checking patch tests/posix/common/testcase.yaml...
Hunk #1 succeeded at 37 (offset 1 line).
```

**Comment by cfriedt** [comment]
@anujdeshpande - it looks like `fn_abort` was removed in Zephyr commit zephyrproject-rtos/zephyr@c0c8cb0e97617c6b35fc8f27de8c82d74ada11fc .

Likely your build / PR will work if you change `master` to zephyrproject-rtos/zephyr@fc1b5de4c307a97023520f27058f19db09c4face in `west.yml`.

This unfortunately pins greybus-for-zephyr to a specific Zephyr commit. A fix for issue #10 should eliminate the issue entirely.

**Comment by anujdeshpande** [comment]
@cfriedt thanks for the pointer to the commit. Pinning that in `west.yml` got me to building it the uart sample correctly for  cc1352 sensor tag. I've updated my commit for this PR to remove the patch change, and change the west.yml instead.

**Comment by cfriedt** [comment]
Thanks for your PR @anujdeshpande !

**Pull request merged**
